### ISSUE TITLE
Higher threshold for winning three stars

### ISSUE THREAD

**Issue by Dagi93** [FabianIAM12/memory-game#1]
https://github.com/FabianIAM12/memory-game/blob/80df08ecb7818cd272535babc141e79ad2b6e810/js/app.js#L45

You should really consider to raise the threshold needed to get three stars. 11 moves might be a good start.

**Comment by FabianIAM12** [comment]
To prevent high frustration with bad skilled noobs, i took 13. Thanks for your contribution. I'm looking forward for your first pull request.

Its implemented.
